---
# https://www.dotdeb.org/instructions/
- name: Ensure dotdeb repository key is installed.
  apt_key:
    url: "{{ apt_extra_sources_dotdeb_key_url }}"

- name: Ensure dotdeb APT repository list is installed.
  apt_repository:
    repo: "{{ apt_extra_sources_dotdeb_repo }}"
    update_cache: no
  register: _apt_extra_sources_changed

- set_fact: apt_extra_sources_changed=yes
  when: _apt_extra_sources_changed.changed
