---

- set_fact: apt_extra_sources_changed=no

- include: mariadb.yml
  when: apt_extra_sources_mariadb
- include: mysql.yml
  when: apt_extra_sources_mysql
- include: nginx.yml
  when: apt_extra_sources_nginx
- include: php71.yml
  when: apt_extra_sources_php71 and ansible_distribution_release in ["jessie", "stretch"]
- include: postgresql.yml
  when: apt_extra_sources_postgresql
- include: tor.yml
  when: apt_extra_sources_tor
- include: sources.yml

- name: Update cache if sources changed
  apt: update_cache=yes
  changed_when: no
  when: apt_extra_sources_changed == True
