---
# Distribution limits are given by the availability of the packages themselves.

- set_fact: apt_extra_sources_changed=no

- name: Update cache and ensure necessary APT packages are installed
  apt: name="{{ item }}" update_cache=yes cache_valid_time=86400
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg

- include: dotdeb.yml
  when: apt_extra_sources_dotdeb and ansible_distribution == "Debian"
- include: mariadb.yml
  when: apt_extra_sources_mariadb
- include: mysql.yml
  when: apt_extra_sources_mysql
- include: nginx.yml
  when: apt_extra_sources_nginx
- include: php71.yml
  when: apt_extra_sources_php71 and ansible_distribution == "Debian"
- include: postgresql.yml
  when: apt_extra_sources_postgresql
- include: tor.yml
  when: apt_extra_sources_tor
- include: sources.yml

- name: Update cache if sources changed
  apt: update_cache=yes
  changed_when: no
  when: apt_extra_sources_changed == True
