---
# https://downloads.mariadb.org/mariadb/repositories/
- name: Ensure MariaDB repository key is installed.
  apt_key:
    keyserver: "{{ extra_sources_mariadb_key_server }}"
    id: "{{ extra_sources_mariadb_key_id }}"

- name: Ensure MariaDB APT repository list is installed.
  apt_repository:
    repo: "{{ extra_sources_mariadb_repo }}"
    update_cache: no
  register: _extra_sources_changed

- set_fact: extra_sources_changed=yes
  when: _extra_sources_changed.changed
