---
# https://downloads.mariadb.org/mariadb/repositories/
- name: Ensure MariaDB repository key is installed.
  apt_key:
    keyserver: "{{ apt_extra_sources_mariadb_key_server }}"
    id: "{{ apt_extra_sources_mariadb_key_id }}"

- name: Ensure MariaDB APT repository list is installed.
  apt_repository:
    repo: "{{ apt_extra_sources_mariadb_repo }}"
    update_cache: no
  register: _apt_extra_sources_changed

- set_fact: apt_extra_sources_changed=yes
  when: _apt_extra_sources_changed.changed
