---
# https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup
- name: Ensure MySQL repository key is installed.
  apt_key:
    keyserver: "{{ extra_sources_mysql_key_server }}"
    id: "{{ extra_sources_mysql_key_id }}"

- name: Ensure MySQL APT repository list is installed.
  apt_repository:
    repo: "{{ extra_sources_mysql_repo }}"
    update_cache: no
  register: _extra_sources_changed

- set_fact: extra_sources_changed=yes
  when: _extra_sources_changed.changed
