---
# https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup
- name: Ensure MySQL repository key is installed.
  apt_key:
    keyserver: "{{ apt_extra_sources_mysql_key_server }}"
    id: "{{ apt_extra_sources_mysql_key_id }}"

- name: Ensure MySQL APT repository list is installed.
  apt_repository:
    repo: "{{ apt_extra_sources_mysql_repo }}"
    update_cache: no
  register: _apt_extra_sources_changed

- set_fact: apt_extra_sources_changed=yes
  when: _apt_extra_sources_changed.changed
