---
# https://nginx.org/en/linux_packages.html#stable
- name: Ensure Nginx repository key is installed.
  apt_key:
    url: "{{ apt_extra_sources_nginx_key_url }}"

- name: Ensure Nginx APT repository list is installed.
  apt_repository:
    repo: "{{ apt_extra_sources_nginx_repo }}"
    update_cache: no
  register: _apt_extra_sources_changed

- set_fact: apt_extra_sources_changed=yes
  when: _apt_extra_sources_changed.changed
