---
# https://www.torproject.org/docs/debian.html.en
- name: Ensure necessary APT packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - deb.torproject.org-keyring

- name: Ensure (custom) Tor repository key is installed.
  apt_key:
    keyserver: "{{ apt_extra_sources_tor_key_server }}"
    id: "{{ apt_extra_sources_tor_key_id }}"
  when: apt_extra_sources_tor_key_id | default('', True) | length > 0

- name: Ensure Tor APT repository list is installed.
  apt_repository:
    repo: "{{ apt_extra_sources_tor_repo }}"
    update_cache: no
  register: _apt_extra_sources_changed

- set_fact: apt_extra_sources_changed=yes
  when: _apt_extra_sources_changed.changed
